/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTailoredResumeRouteImport } from './routes/api.tailored-resume'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedApplyRouteImport } from './routes/_authenticated/apply'
import { Route as AuthenticatedApplyIndexRouteImport } from './routes/_authenticated/apply.index'
import { Route as AuthenticatedApplyTailorRouteImport } from './routes/_authenticated/apply.tailor'
import { Route as AuthenticatedApplyReferralsRouteImport } from './routes/_authenticated/apply.referrals'
import { Route as AuthenticatedApplyMetricsRouteImport } from './routes/_authenticated/apply.metrics'
import { Route as AuthenticatedApplyMatchesRouteImport } from './routes/_authenticated/apply.matches'
import { Route as AuthenticatedApplyAutofillRouteImport } from './routes/_authenticated/apply.autofill'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTailoredResumeRoute = ApiTailoredResumeRouteImport.update({
  id: '/api/tailored-resume',
  path: '/api/tailored-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/_authenticated/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplyRoute = AuthenticatedApplyRouteImport.update({
  id: '/_authenticated/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplyIndexRoute = AuthenticatedApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedApplyRoute,
} as any)
const AuthenticatedApplyTailorRoute =
  AuthenticatedApplyTailorRouteImport.update({
    id: '/tailor',
    path: '/tailor',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyReferralsRoute =
  AuthenticatedApplyReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyMetricsRoute =
  AuthenticatedApplyMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyMatchesRoute =
  AuthenticatedApplyMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyAutofillRoute =
  AuthenticatedApplyAutofillRouteImport.update({
    id: '/autofill',
    path: '/autofill',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof AuthenticatedApplyRouteWithChildren
  '/resume': typeof AuthenticatedResumeRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/apply/autofill': typeof AuthenticatedApplyAutofillRoute
  '/apply/matches': typeof AuthenticatedApplyMatchesRoute
  '/apply/metrics': typeof AuthenticatedApplyMetricsRoute
  '/apply/referrals': typeof AuthenticatedApplyReferralsRoute
  '/apply/tailor': typeof AuthenticatedApplyTailorRoute
  '/apply/': typeof AuthenticatedApplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/apply/autofill': typeof AuthenticatedApplyAutofillRoute
  '/apply/matches': typeof AuthenticatedApplyMatchesRoute
  '/apply/metrics': typeof AuthenticatedApplyMetricsRoute
  '/apply/referrals': typeof AuthenticatedApplyReferralsRoute
  '/apply/tailor': typeof AuthenticatedApplyTailorRoute
  '/apply': typeof AuthenticatedApplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/apply': typeof AuthenticatedApplyRouteWithChildren
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/_authenticated/apply/autofill': typeof AuthenticatedApplyAutofillRoute
  '/_authenticated/apply/matches': typeof AuthenticatedApplyMatchesRoute
  '/_authenticated/apply/metrics': typeof AuthenticatedApplyMetricsRoute
  '/_authenticated/apply/referrals': typeof AuthenticatedApplyReferralsRoute
  '/_authenticated/apply/tailor': typeof AuthenticatedApplyTailorRoute
  '/_authenticated/apply/': typeof AuthenticatedApplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/resume'
    | '/api/tailored-resume'
    | '/apply/autofill'
    | '/apply/matches'
    | '/apply/metrics'
    | '/apply/referrals'
    | '/apply/tailor'
    | '/apply/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/api/tailored-resume'
    | '/apply/autofill'
    | '/apply/matches'
    | '/apply/metrics'
    | '/apply/referrals'
    | '/apply/tailor'
    | '/apply'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/apply'
    | '/_authenticated/resume'
    | '/api/tailored-resume'
    | '/_authenticated/apply/autofill'
    | '/_authenticated/apply/matches'
    | '/_authenticated/apply/metrics'
    | '/_authenticated/apply/referrals'
    | '/_authenticated/apply/tailor'
    | '/_authenticated/apply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedApplyRoute: typeof AuthenticatedApplyRouteWithChildren
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  ApiTailoredResumeRoute: typeof ApiTailoredResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tailored-resume': {
      id: '/api/tailored-resume'
      path: '/api/tailored-resume'
      fullPath: '/api/tailored-resume'
      preLoaderRoute: typeof ApiTailoredResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apply': {
      id: '/_authenticated/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthenticatedApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apply/': {
      id: '/_authenticated/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof AuthenticatedApplyIndexRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/tailor': {
      id: '/_authenticated/apply/tailor'
      path: '/tailor'
      fullPath: '/apply/tailor'
      preLoaderRoute: typeof AuthenticatedApplyTailorRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/referrals': {
      id: '/_authenticated/apply/referrals'
      path: '/referrals'
      fullPath: '/apply/referrals'
      preLoaderRoute: typeof AuthenticatedApplyReferralsRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/metrics': {
      id: '/_authenticated/apply/metrics'
      path: '/metrics'
      fullPath: '/apply/metrics'
      preLoaderRoute: typeof AuthenticatedApplyMetricsRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/matches': {
      id: '/_authenticated/apply/matches'
      path: '/matches'
      fullPath: '/apply/matches'
      preLoaderRoute: typeof AuthenticatedApplyMatchesRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/autofill': {
      id: '/_authenticated/apply/autofill'
      path: '/autofill'
      fullPath: '/apply/autofill'
      preLoaderRoute: typeof AuthenticatedApplyAutofillRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
  }
}

interface AuthenticatedApplyRouteChildren {
  AuthenticatedApplyAutofillRoute: typeof AuthenticatedApplyAutofillRoute
  AuthenticatedApplyMatchesRoute: typeof AuthenticatedApplyMatchesRoute
  AuthenticatedApplyMetricsRoute: typeof AuthenticatedApplyMetricsRoute
  AuthenticatedApplyReferralsRoute: typeof AuthenticatedApplyReferralsRoute
  AuthenticatedApplyTailorRoute: typeof AuthenticatedApplyTailorRoute
  AuthenticatedApplyIndexRoute: typeof AuthenticatedApplyIndexRoute
}

const AuthenticatedApplyRouteChildren: AuthenticatedApplyRouteChildren = {
  AuthenticatedApplyAutofillRoute: AuthenticatedApplyAutofillRoute,
  AuthenticatedApplyMatchesRoute: AuthenticatedApplyMatchesRoute,
  AuthenticatedApplyMetricsRoute: AuthenticatedApplyMetricsRoute,
  AuthenticatedApplyReferralsRoute: AuthenticatedApplyReferralsRoute,
  AuthenticatedApplyTailorRoute: AuthenticatedApplyTailorRoute,
  AuthenticatedApplyIndexRoute: AuthenticatedApplyIndexRoute,
}

const AuthenticatedApplyRouteWithChildren =
  AuthenticatedApplyRoute._addFileChildren(AuthenticatedApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedApplyRoute: AuthenticatedApplyRouteWithChildren,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  ApiTailoredResumeRoute: ApiTailoredResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
