/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ChristopherRouteImport } from './routes/christopher'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpGettingStartedRouteImport } from './routes/help.getting-started'
import { Route as HelpFaqRouteImport } from './routes/help.faq'
import { Route as ApiTailoredResumeRouteImport } from './routes/api.tailored-resume'
import { Route as ApiResumeDocxRouteImport } from './routes/api.resume-docx'
import { Route as ApiExtractRouteImport } from './routes/api.extract'
import { Route as ApiExportRouteImport } from './routes/api.export'
import { Route as ApiCoverLetterPdfRouteImport } from './routes/api.cover-letter-pdf'
import { Route as ApiCoverLetterDocxRouteImport } from './routes/api.cover-letter-docx'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AuthenticatedWhatsNewRouteImport } from './routes/_authenticated/whats-new'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedApplyRouteImport } from './routes/_authenticated/apply'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedApplyIndexRouteImport } from './routes/_authenticated/apply.index'
import { Route as ApiOwnerMetricsRouteImport } from './routes/api/owner/metrics'
import { Route as ApiExtensionProfileRouteImport } from './routes/api.extension.profile'
import { Route as AuthenticatedApplyTailorRouteImport } from './routes/_authenticated/apply.tailor'
import { Route as AuthenticatedApplyRewriteRouteImport } from './routes/_authenticated/apply.rewrite'
import { Route as AuthenticatedApplyReferralsRouteImport } from './routes/_authenticated/apply.referrals'
import { Route as AuthenticatedApplyMetricsRouteImport } from './routes/_authenticated/apply.metrics'
import { Route as AuthenticatedApplyMatchesRouteImport } from './routes/_authenticated/apply.matches'
import { Route as AuthenticatedApplyInterviewPrepRouteImport } from './routes/_authenticated/apply.interview-prep'
import { Route as AuthenticatedApplyGoRouteImport } from './routes/_authenticated/apply.go'
import { Route as AuthenticatedApplyDiscoverRouteImport } from './routes/_authenticated/apply.discover'
import { Route as AuthenticatedApplyAutofillRouteImport } from './routes/_authenticated/apply.autofill'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicOwnerMetricsRouteImport } from './routes/api/public/owner/metrics'
import { Route as ApiPublicHooksWeeklyDigestRouteImport } from './routes/api/public/hooks/weekly-digest'
import { Route as ApiPublicHooksUnsubscribeRouteImport } from './routes/api/public/hooks/unsubscribe'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicHooksRefreshJobsRouteImport } from './routes/api/public/hooks/refresh-jobs'
import { Route as ApiPublicHooksRankJobsRouteImport } from './routes/api/public/hooks/rank-jobs'
import { Route as ApiPublicHooksCleanupRouteImport } from './routes/api/public/hooks/cleanup'
import { Route as AuthenticatedAdminAdminInvitesRouteImport } from './routes/_authenticated/_admin/admin.invites'

const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ChristopherRoute = ChristopherRouteImport.update({
  id: '/christopher',
  path: '/christopher',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpGettingStartedRoute = HelpGettingStartedRouteImport.update({
  id: '/help/getting-started',
  path: '/help/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpFaqRoute = HelpFaqRouteImport.update({
  id: '/help/faq',
  path: '/help/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTailoredResumeRoute = ApiTailoredResumeRouteImport.update({
  id: '/api/tailored-resume',
  path: '/api/tailored-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeDocxRoute = ApiResumeDocxRouteImport.update({
  id: '/api/resume-docx',
  path: '/api/resume-docx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoverLetterPdfRoute = ApiCoverLetterPdfRouteImport.update({
  id: '/api/cover-letter-pdf',
  path: '/api/cover-letter-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoverLetterDocxRoute = ApiCoverLetterDocxRouteImport.update({
  id: '/api/cover-letter-docx',
  path: '/api/cover-letter-docx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsNewRoute = AuthenticatedWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyRoute = AuthenticatedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyIndexRoute = AuthenticatedApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedApplyRoute,
} as any)
const ApiOwnerMetricsRoute = ApiOwnerMetricsRouteImport.update({
  id: '/api/owner/metrics',
  path: '/api/owner/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionProfileRoute = ApiExtensionProfileRouteImport.update({
  id: '/api/extension/profile',
  path: '/api/extension/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplyTailorRoute =
  AuthenticatedApplyTailorRouteImport.update({
    id: '/tailor',
    path: '/tailor',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyRewriteRoute =
  AuthenticatedApplyRewriteRouteImport.update({
    id: '/rewrite',
    path: '/rewrite',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyReferralsRoute =
  AuthenticatedApplyReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyMetricsRoute =
  AuthenticatedApplyMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyMatchesRoute =
  AuthenticatedApplyMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyInterviewPrepRoute =
  AuthenticatedApplyInterviewPrepRouteImport.update({
    id: '/interview-prep',
    path: '/interview-prep',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyGoRoute = AuthenticatedApplyGoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => AuthenticatedApplyRoute,
} as any)
const AuthenticatedApplyDiscoverRoute =
  AuthenticatedApplyDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const AuthenticatedApplyAutofillRoute =
  AuthenticatedApplyAutofillRouteImport.update({
    id: '/autofill',
    path: '/autofill',
    getParentRoute: () => AuthenticatedApplyRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOwnerMetricsRoute = ApiPublicOwnerMetricsRouteImport.update({
  id: '/api/public/owner/metrics',
  path: '/api/public/owner/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyDigestRoute =
  ApiPublicHooksWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/weekly-digest',
    path: '/api/public/hooks/weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksUnsubscribeRoute =
  ApiPublicHooksUnsubscribeRouteImport.update({
    id: '/api/public/hooks/unsubscribe',
    path: '/api/public/hooks/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshJobsRoute =
  ApiPublicHooksRefreshJobsRouteImport.update({
    id: '/api/public/hooks/refresh-jobs',
    path: '/api/public/hooks/refresh-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRankJobsRoute = ApiPublicHooksRankJobsRouteImport.update({
  id: '/api/public/hooks/rank-jobs',
  path: '/api/public/hooks/rank-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupRoute = ApiPublicHooksCleanupRouteImport.update({
  id: '/api/public/hooks/cleanup',
  path: '/api/public/hooks/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminInvitesRoute =
  AuthenticatedAdminAdminInvitesRouteImport.update({
    id: '/admin/invites',
    path: '/admin/invites',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/christopher': typeof ChristopherRoute
  '/legal': typeof LegalRoute
  '/mcp': typeof McpRoute
  '/request-access': typeof RequestAccessRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/apply': typeof AuthenticatedApplyRouteWithChildren
  '/resume': typeof AuthenticatedResumeRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cover-letter-docx': typeof ApiCoverLetterDocxRoute
  '/api/cover-letter-pdf': typeof ApiCoverLetterPdfRoute
  '/api/export': typeof ApiExportRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/resume-docx': typeof ApiResumeDocxRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/getting-started': typeof HelpGettingStartedRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/apply/autofill': typeof AuthenticatedApplyAutofillRoute
  '/apply/discover': typeof AuthenticatedApplyDiscoverRoute
  '/apply/go': typeof AuthenticatedApplyGoRoute
  '/apply/interview-prep': typeof AuthenticatedApplyInterviewPrepRoute
  '/apply/matches': typeof AuthenticatedApplyMatchesRoute
  '/apply/metrics': typeof AuthenticatedApplyMetricsRoute
  '/apply/referrals': typeof AuthenticatedApplyReferralsRoute
  '/apply/rewrite': typeof AuthenticatedApplyRewriteRoute
  '/apply/tailor': typeof AuthenticatedApplyTailorRoute
  '/api/extension/profile': typeof ApiExtensionProfileRoute
  '/api/owner/metrics': typeof ApiOwnerMetricsRoute
  '/apply/': typeof AuthenticatedApplyIndexRoute
  '/admin/invites': typeof AuthenticatedAdminAdminInvitesRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
  '/api/public/hooks/rank-jobs': typeof ApiPublicHooksRankJobsRoute
  '/api/public/hooks/refresh-jobs': typeof ApiPublicHooksRefreshJobsRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/unsubscribe': typeof ApiPublicHooksUnsubscribeRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/api/public/owner/metrics': typeof ApiPublicOwnerMetricsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/christopher': typeof ChristopherRoute
  '/legal': typeof LegalRoute
  '/mcp': typeof McpRoute
  '/request-access': typeof RequestAccessRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cover-letter-docx': typeof ApiCoverLetterDocxRoute
  '/api/cover-letter-pdf': typeof ApiCoverLetterPdfRoute
  '/api/export': typeof ApiExportRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/resume-docx': typeof ApiResumeDocxRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/getting-started': typeof HelpGettingStartedRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/apply/autofill': typeof AuthenticatedApplyAutofillRoute
  '/apply/discover': typeof AuthenticatedApplyDiscoverRoute
  '/apply/go': typeof AuthenticatedApplyGoRoute
  '/apply/interview-prep': typeof AuthenticatedApplyInterviewPrepRoute
  '/apply/matches': typeof AuthenticatedApplyMatchesRoute
  '/apply/metrics': typeof AuthenticatedApplyMetricsRoute
  '/apply/referrals': typeof AuthenticatedApplyReferralsRoute
  '/apply/rewrite': typeof AuthenticatedApplyRewriteRoute
  '/apply/tailor': typeof AuthenticatedApplyTailorRoute
  '/api/extension/profile': typeof ApiExtensionProfileRoute
  '/api/owner/metrics': typeof ApiOwnerMetricsRoute
  '/apply': typeof AuthenticatedApplyIndexRoute
  '/admin/invites': typeof AuthenticatedAdminAdminInvitesRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
  '/api/public/hooks/rank-jobs': typeof ApiPublicHooksRankJobsRoute
  '/api/public/hooks/refresh-jobs': typeof ApiPublicHooksRefreshJobsRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/unsubscribe': typeof ApiPublicHooksUnsubscribeRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/api/public/owner/metrics': typeof ApiPublicOwnerMetricsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/christopher': typeof ChristopherRoute
  '/legal': typeof LegalRoute
  '/mcp': typeof McpRoute
  '/request-access': typeof RequestAccessRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/apply': typeof AuthenticatedApplyRouteWithChildren
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/whats-new': typeof AuthenticatedWhatsNewRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cover-letter-docx': typeof ApiCoverLetterDocxRoute
  '/api/cover-letter-pdf': typeof ApiCoverLetterPdfRoute
  '/api/export': typeof ApiExportRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/resume-docx': typeof ApiResumeDocxRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/getting-started': typeof HelpGettingStartedRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/apply/autofill': typeof AuthenticatedApplyAutofillRoute
  '/_authenticated/apply/discover': typeof AuthenticatedApplyDiscoverRoute
  '/_authenticated/apply/go': typeof AuthenticatedApplyGoRoute
  '/_authenticated/apply/interview-prep': typeof AuthenticatedApplyInterviewPrepRoute
  '/_authenticated/apply/matches': typeof AuthenticatedApplyMatchesRoute
  '/_authenticated/apply/metrics': typeof AuthenticatedApplyMetricsRoute
  '/_authenticated/apply/referrals': typeof AuthenticatedApplyReferralsRoute
  '/_authenticated/apply/rewrite': typeof AuthenticatedApplyRewriteRoute
  '/_authenticated/apply/tailor': typeof AuthenticatedApplyTailorRoute
  '/api/extension/profile': typeof ApiExtensionProfileRoute
  '/api/owner/metrics': typeof ApiOwnerMetricsRoute
  '/_authenticated/apply/': typeof AuthenticatedApplyIndexRoute
  '/_authenticated/_admin/admin/invites': typeof AuthenticatedAdminAdminInvitesRoute
  '/api/public/hooks/cleanup': typeof ApiPublicHooksCleanupRoute
  '/api/public/hooks/rank-jobs': typeof ApiPublicHooksRankJobsRoute
  '/api/public/hooks/refresh-jobs': typeof ApiPublicHooksRefreshJobsRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/unsubscribe': typeof ApiPublicHooksUnsubscribeRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
  '/api/public/owner/metrics': typeof ApiPublicOwnerMetricsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/christopher'
    | '/legal'
    | '/mcp'
    | '/request-access'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/apply'
    | '/resume'
    | '/resumes'
    | '/settings'
    | '/whats-new'
    | '/api/chat'
    | '/api/cover-letter-docx'
    | '/api/cover-letter-pdf'
    | '/api/export'
    | '/api/extract'
    | '/api/resume-docx'
    | '/api/tailored-resume'
    | '/help/faq'
    | '/help/getting-started'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/apply/autofill'
    | '/apply/discover'
    | '/apply/go'
    | '/apply/interview-prep'
    | '/apply/matches'
    | '/apply/metrics'
    | '/apply/referrals'
    | '/apply/rewrite'
    | '/apply/tailor'
    | '/api/extension/profile'
    | '/api/owner/metrics'
    | '/apply/'
    | '/admin/invites'
    | '/api/public/hooks/cleanup'
    | '/api/public/hooks/rank-jobs'
    | '/api/public/hooks/refresh-jobs'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/unsubscribe'
    | '/api/public/hooks/weekly-digest'
    | '/api/public/owner/metrics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/christopher'
    | '/legal'
    | '/mcp'
    | '/request-access'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/resume'
    | '/resumes'
    | '/settings'
    | '/whats-new'
    | '/api/chat'
    | '/api/cover-letter-docx'
    | '/api/cover-letter-pdf'
    | '/api/export'
    | '/api/extract'
    | '/api/resume-docx'
    | '/api/tailored-resume'
    | '/help/faq'
    | '/help/getting-started'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/apply/autofill'
    | '/apply/discover'
    | '/apply/go'
    | '/apply/interview-prep'
    | '/apply/matches'
    | '/apply/metrics'
    | '/apply/referrals'
    | '/apply/rewrite'
    | '/apply/tailor'
    | '/api/extension/profile'
    | '/api/owner/metrics'
    | '/apply'
    | '/admin/invites'
    | '/api/public/hooks/cleanup'
    | '/api/public/hooks/rank-jobs'
    | '/api/public/hooks/refresh-jobs'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/unsubscribe'
    | '/api/public/hooks/weekly-digest'
    | '/api/public/owner/metrics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/christopher'
    | '/legal'
    | '/mcp'
    | '/request-access'
    | '/_authenticated/_admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/apply'
    | '/_authenticated/resume'
    | '/_authenticated/resumes'
    | '/_authenticated/settings'
    | '/_authenticated/whats-new'
    | '/api/chat'
    | '/api/cover-letter-docx'
    | '/api/cover-letter-pdf'
    | '/api/export'
    | '/api/extract'
    | '/api/resume-docx'
    | '/api/tailored-resume'
    | '/help/faq'
    | '/help/getting-started'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/apply/autofill'
    | '/_authenticated/apply/discover'
    | '/_authenticated/apply/go'
    | '/_authenticated/apply/interview-prep'
    | '/_authenticated/apply/matches'
    | '/_authenticated/apply/metrics'
    | '/_authenticated/apply/referrals'
    | '/_authenticated/apply/rewrite'
    | '/_authenticated/apply/tailor'
    | '/api/extension/profile'
    | '/api/owner/metrics'
    | '/_authenticated/apply/'
    | '/_authenticated/_admin/admin/invites'
    | '/api/public/hooks/cleanup'
    | '/api/public/hooks/rank-jobs'
    | '/api/public/hooks/refresh-jobs'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/unsubscribe'
    | '/api/public/hooks/weekly-digest'
    | '/api/public/owner/metrics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChristopherRoute: typeof ChristopherRoute
  LegalRoute: typeof LegalRoute
  McpRoute: typeof McpRoute
  RequestAccessRoute: typeof RequestAccessRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCoverLetterDocxRoute: typeof ApiCoverLetterDocxRoute
  ApiCoverLetterPdfRoute: typeof ApiCoverLetterPdfRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiResumeDocxRoute: typeof ApiResumeDocxRoute
  ApiTailoredResumeRoute: typeof ApiTailoredResumeRoute
  HelpFaqRoute: typeof HelpFaqRoute
  HelpGettingStartedRoute: typeof HelpGettingStartedRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiExtensionProfileRoute: typeof ApiExtensionProfileRoute
  ApiOwnerMetricsRoute: typeof ApiOwnerMetricsRoute
  ApiPublicHooksCleanupRoute: typeof ApiPublicHooksCleanupRoute
  ApiPublicHooksRankJobsRoute: typeof ApiPublicHooksRankJobsRoute
  ApiPublicHooksRefreshJobsRoute: typeof ApiPublicHooksRefreshJobsRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
  ApiPublicHooksUnsubscribeRoute: typeof ApiPublicHooksUnsubscribeRoute
  ApiPublicHooksWeeklyDigestRoute: typeof ApiPublicHooksWeeklyDigestRoute
  ApiPublicOwnerMetricsRoute: typeof ApiPublicOwnerMetricsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/christopher': {
      id: '/christopher'
      path: '/christopher'
      fullPath: '/christopher'
      preLoaderRoute: typeof ChristopherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/getting-started': {
      id: '/help/getting-started'
      path: '/help/getting-started'
      fullPath: '/help/getting-started'
      preLoaderRoute: typeof HelpGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/faq': {
      id: '/help/faq'
      path: '/help/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof HelpFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tailored-resume': {
      id: '/api/tailored-resume'
      path: '/api/tailored-resume'
      fullPath: '/api/tailored-resume'
      preLoaderRoute: typeof ApiTailoredResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-docx': {
      id: '/api/resume-docx'
      path: '/api/resume-docx'
      fullPath: '/api/resume-docx'
      preLoaderRoute: typeof ApiResumeDocxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cover-letter-pdf': {
      id: '/api/cover-letter-pdf'
      path: '/api/cover-letter-pdf'
      fullPath: '/api/cover-letter-pdf'
      preLoaderRoute: typeof ApiCoverLetterPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cover-letter-docx': {
      id: '/api/cover-letter-docx'
      path: '/api/cover-letter-docx'
      fullPath: '/api/cover-letter-docx'
      preLoaderRoute: typeof ApiCoverLetterDocxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whats-new': {
      id: '/_authenticated/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof AuthenticatedWhatsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply': {
      id: '/_authenticated/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthenticatedApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/': {
      id: '/_authenticated/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof AuthenticatedApplyIndexRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/api/owner/metrics': {
      id: '/api/owner/metrics'
      path: '/api/owner/metrics'
      fullPath: '/api/owner/metrics'
      preLoaderRoute: typeof ApiOwnerMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/profile': {
      id: '/api/extension/profile'
      path: '/api/extension/profile'
      fullPath: '/api/extension/profile'
      preLoaderRoute: typeof ApiExtensionProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apply/tailor': {
      id: '/_authenticated/apply/tailor'
      path: '/tailor'
      fullPath: '/apply/tailor'
      preLoaderRoute: typeof AuthenticatedApplyTailorRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/rewrite': {
      id: '/_authenticated/apply/rewrite'
      path: '/rewrite'
      fullPath: '/apply/rewrite'
      preLoaderRoute: typeof AuthenticatedApplyRewriteRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/referrals': {
      id: '/_authenticated/apply/referrals'
      path: '/referrals'
      fullPath: '/apply/referrals'
      preLoaderRoute: typeof AuthenticatedApplyReferralsRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/metrics': {
      id: '/_authenticated/apply/metrics'
      path: '/metrics'
      fullPath: '/apply/metrics'
      preLoaderRoute: typeof AuthenticatedApplyMetricsRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/matches': {
      id: '/_authenticated/apply/matches'
      path: '/matches'
      fullPath: '/apply/matches'
      preLoaderRoute: typeof AuthenticatedApplyMatchesRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/interview-prep': {
      id: '/_authenticated/apply/interview-prep'
      path: '/interview-prep'
      fullPath: '/apply/interview-prep'
      preLoaderRoute: typeof AuthenticatedApplyInterviewPrepRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/go': {
      id: '/_authenticated/apply/go'
      path: '/go'
      fullPath: '/apply/go'
      preLoaderRoute: typeof AuthenticatedApplyGoRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/discover': {
      id: '/_authenticated/apply/discover'
      path: '/discover'
      fullPath: '/apply/discover'
      preLoaderRoute: typeof AuthenticatedApplyDiscoverRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/_authenticated/apply/autofill': {
      id: '/_authenticated/apply/autofill'
      path: '/autofill'
      fullPath: '/apply/autofill'
      preLoaderRoute: typeof AuthenticatedApplyAutofillRouteImport
      parentRoute: typeof AuthenticatedApplyRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/owner/metrics': {
      id: '/api/public/owner/metrics'
      path: '/api/public/owner/metrics'
      fullPath: '/api/public/owner/metrics'
      preLoaderRoute: typeof ApiPublicOwnerMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-digest': {
      id: '/api/public/hooks/weekly-digest'
      path: '/api/public/hooks/weekly-digest'
      fullPath: '/api/public/hooks/weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/unsubscribe': {
      id: '/api/public/hooks/unsubscribe'
      path: '/api/public/hooks/unsubscribe'
      fullPath: '/api/public/hooks/unsubscribe'
      preLoaderRoute: typeof ApiPublicHooksUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-jobs': {
      id: '/api/public/hooks/refresh-jobs'
      path: '/api/public/hooks/refresh-jobs'
      fullPath: '/api/public/hooks/refresh-jobs'
      preLoaderRoute: typeof ApiPublicHooksRefreshJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rank-jobs': {
      id: '/api/public/hooks/rank-jobs'
      path: '/api/public/hooks/rank-jobs'
      fullPath: '/api/public/hooks/rank-jobs'
      preLoaderRoute: typeof ApiPublicHooksRankJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup': {
      id: '/api/public/hooks/cleanup'
      path: '/api/public/hooks/cleanup'
      fullPath: '/api/public/hooks/cleanup'
      preLoaderRoute: typeof ApiPublicHooksCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/invites': {
      id: '/_authenticated/_admin/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminInvitesRoute: typeof AuthenticatedAdminAdminInvitesRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminInvitesRoute: AuthenticatedAdminAdminInvitesRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedApplyRouteChildren {
  AuthenticatedApplyAutofillRoute: typeof AuthenticatedApplyAutofillRoute
  AuthenticatedApplyDiscoverRoute: typeof AuthenticatedApplyDiscoverRoute
  AuthenticatedApplyGoRoute: typeof AuthenticatedApplyGoRoute
  AuthenticatedApplyInterviewPrepRoute: typeof AuthenticatedApplyInterviewPrepRoute
  AuthenticatedApplyMatchesRoute: typeof AuthenticatedApplyMatchesRoute
  AuthenticatedApplyMetricsRoute: typeof AuthenticatedApplyMetricsRoute
  AuthenticatedApplyReferralsRoute: typeof AuthenticatedApplyReferralsRoute
  AuthenticatedApplyRewriteRoute: typeof AuthenticatedApplyRewriteRoute
  AuthenticatedApplyTailorRoute: typeof AuthenticatedApplyTailorRoute
  AuthenticatedApplyIndexRoute: typeof AuthenticatedApplyIndexRoute
}

const AuthenticatedApplyRouteChildren: AuthenticatedApplyRouteChildren = {
  AuthenticatedApplyAutofillRoute: AuthenticatedApplyAutofillRoute,
  AuthenticatedApplyDiscoverRoute: AuthenticatedApplyDiscoverRoute,
  AuthenticatedApplyGoRoute: AuthenticatedApplyGoRoute,
  AuthenticatedApplyInterviewPrepRoute: AuthenticatedApplyInterviewPrepRoute,
  AuthenticatedApplyMatchesRoute: AuthenticatedApplyMatchesRoute,
  AuthenticatedApplyMetricsRoute: AuthenticatedApplyMetricsRoute,
  AuthenticatedApplyReferralsRoute: AuthenticatedApplyReferralsRoute,
  AuthenticatedApplyRewriteRoute: AuthenticatedApplyRewriteRoute,
  AuthenticatedApplyTailorRoute: AuthenticatedApplyTailorRoute,
  AuthenticatedApplyIndexRoute: AuthenticatedApplyIndexRoute,
}

const AuthenticatedApplyRouteWithChildren =
  AuthenticatedApplyRoute._addFileChildren(AuthenticatedApplyRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedApplyRoute: typeof AuthenticatedApplyRouteWithChildren
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWhatsNewRoute: typeof AuthenticatedWhatsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedApplyRoute: AuthenticatedApplyRouteWithChildren,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWhatsNewRoute: AuthenticatedWhatsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChristopherRoute: ChristopherRoute,
  LegalRoute: LegalRoute,
  McpRoute: McpRoute,
  RequestAccessRoute: RequestAccessRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCoverLetterDocxRoute: ApiCoverLetterDocxRoute,
  ApiCoverLetterPdfRoute: ApiCoverLetterPdfRoute,
  ApiExportRoute: ApiExportRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiResumeDocxRoute: ApiResumeDocxRoute,
  ApiTailoredResumeRoute: ApiTailoredResumeRoute,
  HelpFaqRoute: HelpFaqRoute,
  HelpGettingStartedRoute: HelpGettingStartedRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiExtensionProfileRoute: ApiExtensionProfileRoute,
  ApiOwnerMetricsRoute: ApiOwnerMetricsRoute,
  ApiPublicHooksCleanupRoute: ApiPublicHooksCleanupRoute,
  ApiPublicHooksRankJobsRoute: ApiPublicHooksRankJobsRoute,
  ApiPublicHooksRefreshJobsRoute: ApiPublicHooksRefreshJobsRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
  ApiPublicHooksUnsubscribeRoute: ApiPublicHooksUnsubscribeRoute,
  ApiPublicHooksWeeklyDigestRoute: ApiPublicHooksWeeklyDigestRoute,
  ApiPublicOwnerMetricsRoute: ApiPublicOwnerMetricsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
