/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as ApplyTailorRouteImport } from './routes/apply.tailor'
import { Route as ApplyReferralsRouteImport } from './routes/apply.referrals'
import { Route as ApplyMatchesRouteImport } from './routes/apply.matches'
import { Route as ApplyAutofillRouteImport } from './routes/apply.autofill'
import { Route as ApiTailoredResumeRouteImport } from './routes/api.tailored-resume'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyTailorRoute = ApplyTailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyReferralsRoute = ApplyReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyMatchesRoute = ApplyMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyAutofillRoute = ApplyAutofillRouteImport.update({
  id: '/autofill',
  path: '/autofill',
  getParentRoute: () => ApplyRoute,
} as any)
const ApiTailoredResumeRoute = ApiTailoredResumeRouteImport.update({
  id: '/api/tailored-resume',
  path: '/api/tailored-resume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/resume': typeof ResumeRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/apply/autofill': typeof ApplyAutofillRoute
  '/apply/matches': typeof ApplyMatchesRoute
  '/apply/referrals': typeof ApplyReferralsRoute
  '/apply/tailor': typeof ApplyTailorRoute
  '/apply/': typeof ApplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/apply/autofill': typeof ApplyAutofillRoute
  '/apply/matches': typeof ApplyMatchesRoute
  '/apply/referrals': typeof ApplyReferralsRoute
  '/apply/tailor': typeof ApplyTailorRoute
  '/apply': typeof ApplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/resume': typeof ResumeRoute
  '/api/tailored-resume': typeof ApiTailoredResumeRoute
  '/apply/autofill': typeof ApplyAutofillRoute
  '/apply/matches': typeof ApplyMatchesRoute
  '/apply/referrals': typeof ApplyReferralsRoute
  '/apply/tailor': typeof ApplyTailorRoute
  '/apply/': typeof ApplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/resume'
    | '/api/tailored-resume'
    | '/apply/autofill'
    | '/apply/matches'
    | '/apply/referrals'
    | '/apply/tailor'
    | '/apply/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/api/tailored-resume'
    | '/apply/autofill'
    | '/apply/matches'
    | '/apply/referrals'
    | '/apply/tailor'
    | '/apply'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/resume'
    | '/api/tailored-resume'
    | '/apply/autofill'
    | '/apply/matches'
    | '/apply/referrals'
    | '/apply/tailor'
    | '/apply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  ApiTailoredResumeRoute: typeof ApiTailoredResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/tailor': {
      id: '/apply/tailor'
      path: '/tailor'
      fullPath: '/apply/tailor'
      preLoaderRoute: typeof ApplyTailorRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/referrals': {
      id: '/apply/referrals'
      path: '/referrals'
      fullPath: '/apply/referrals'
      preLoaderRoute: typeof ApplyReferralsRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/matches': {
      id: '/apply/matches'
      path: '/matches'
      fullPath: '/apply/matches'
      preLoaderRoute: typeof ApplyMatchesRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/autofill': {
      id: '/apply/autofill'
      path: '/autofill'
      fullPath: '/apply/autofill'
      preLoaderRoute: typeof ApplyAutofillRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/api/tailored-resume': {
      id: '/api/tailored-resume'
      path: '/api/tailored-resume'
      fullPath: '/api/tailored-resume'
      preLoaderRoute: typeof ApiTailoredResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApplyRouteChildren {
  ApplyAutofillRoute: typeof ApplyAutofillRoute
  ApplyMatchesRoute: typeof ApplyMatchesRoute
  ApplyReferralsRoute: typeof ApplyReferralsRoute
  ApplyTailorRoute: typeof ApplyTailorRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyAutofillRoute: ApplyAutofillRoute,
  ApplyMatchesRoute: ApplyMatchesRoute,
  ApplyReferralsRoute: ApplyReferralsRoute,
  ApplyTailorRoute: ApplyTailorRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRouteWithChildren,
  ResumeRoute: ResumeRoute,
  ApiTailoredResumeRoute: ApiTailoredResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
